config/routes.rb
Rails.application.routes.draw do
  resources :campaign_registrations 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :countries
  devise_for :users #, controllers: { sessions: 'users/registrations' }
  get 'dashboard', to: 'dashes#dashboard'
  resources :dashes 
  resources :campaigns do
   member do
    get 'join'
    get 'leave'
   end
  end
  resources :players
  
  #get 'exit', to: 'sessions#destroy', as: :logout
 
   root "campaigns#index" 
   
  #api
  namespace :api do
    namespace :v1 do
      resources :campaigns
      resources :countries
      resources :players
      resources :dashes
      resources :users
      get 'dashboard', to: 'dashes#dashboard'
    end
  end
   
   # yank later
   resources :neighborhoods
end

app/models/dash.rb
class Dash < ApplicationRecord
  has_many  :userdashes
  has_many  :users, through: :userdashes
  
  # campaigns I run
  has_many :dashcampaigns
  has_many :campaigns, through: :dashcampaigns
  
  # players I run in campaigns
  has_many :dashplayers
  has_many :players, through: :dashplayers
  
  has_many :dashcounts
  has_many :countries, through: :dashcounts

end

app/controllers/api/v1/dashes_controller.rb
class Api::V1::DashesController < Api::V1::BaseController
  def show
    dash = Dash.find(params[:id])

    render(json: Api::V1::DashSerializer.new(dash).to_json)
  end
  
  def index
    dashes = Dash.all

    render(
      json: ActiveModel::ArraySerializer.new(
        dashes,
        each_serializer: Api::V1::DashSerializer,
        root: 'dashes',
      )
    )
  end
end

app/controllers/dashes_controller.rb
require 'DomainIdentities.rb'

class DashesController < ApplicationController

  before_action :set_dash, only: [:show, :dashboard, :edit, :update, :destroy]

  def dashboard
    @user = set_user
    @my_dash = set_dash
    
    @players = @my_dash.players.paginate(page: params[:page], per_page: 5)
    @dash_hosting = @my_dash.campaigns
  end
    
  def index
    @dashes_list = Dash.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def new
    @dash = Dash.new
  end

  def edit
  end

  def create
    @dash = Dash.new(dash_params)

    respond_to do |format|
      if @dash.save
        format.html { redirect_to @dash, notice: 'Dash was successfully created.' }
        format.json { render :show, status: :created, location: @dash }
      else
        format.html { render :new }
        format.json { render json: @dash.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @dash.update!(dash_params)
        format.html { redirect_to @dash, notice: 'Dash was successfully updated.' }
        format.json { render :show, status: :ok, location: @dash }
      else
        format.html { render :edit }
        format.json { render json: @dash.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    
    respond_to do |format|
      if @dash.destroy!
        format.html { redirect_to dashes_url, notice: "Dash was successfully destroyed."}
        format.json { head :no_content }
      else
        format.html { redirect_to dashes_url, notice: 'Dash failed to be destroyed.' }
        format.json { head :no_content } 
      end
    end
  end

  private
  
    def set_user
      @user = current_user || User.find(params[:id])
    end
    
    def set_dash
      @dash = current_user.dashes.first || Dash.create!()
    end

    def dash_params
      params.require(:dash).permit(:id, :name, :dashcampaigns_id, :dashplayers_id) #pulled user_id for player_controller test
    end
end

app/helpers/dashes_helper.rb
module DashesHelper
  
  # def full_title(page_title = "")                     
  #   base_name = 'Basic Borders'
  #   if page_title.empty?   
  #     page_title = base_name
  #   else
  #     page_title + " | " + base_name
  #   end
  # end
  
  def greet_user_message(name, last_login)
    msg = "Welcome #{name}! ... have not heard from you since #{last_login} !!"
  end
end

app/views/dashes/_dash_players.html.haml
%ul
- for players in @dash_playing
  %li= players.name

app/views/dashes/_form.html.haml
= simple_form_for(@dash) do |f|
  = f.error_notification
  - flash.each do |message_type, message|
    %br= "#{message_type} -- #{message}"

  .form-inputs
    = f.input :name
    = f.association :userdashes
    = f.association :dashcampaigns
    = f.association :dashplayers

  .form-actions
    = f.button :submit

app/views/dashes/_list_dashes.html.haml
%table{:class => "table table-striped table-hover"}
  %thead
    %tr
      %th Name
      %th User
      %th Dashcampaigns
      %th Dashplayers
      %th
      %th
      %th

  %tbody
    - @dashes_list.each do |dash|
      %tr
        %td= dash.name
        // %td= dash.user_id
        %td= dash.dashcampaigns.name
        %td= dash.dashplayers.name
        %td= link_to 'Show', dash
        %td= link_to 'Edit', edit_dash_path(dash)
        %td= link_to 'Destroy', dash, :method => :delete, :data => { :confirm => 'Are you sure?' }
= will_paginate @dashes_list

app/views/dashes/dashboard.html.1.haml
= greet_user_message(@my_dash.name, @user.last_sign_in_at)

%h2 My dash: #{@my_dash.name}

%h3 Campaigns I run
= link_to 'Make New Campaign', new_campaign_path, :class => "btn btn-default btn-xs" 
= render partial: 'dash_campaigns'

%h3 Characters I am playing
= link_to 'Join New Game', campaigns_path, :class => "btn btn-default btn-xs" 
// = render partial: 'dash_players'
= render partial: 'shared/player_list', locals: { list: @dash_playing }

app/views/dashes/dashboard.html.haml
= greet_user_message(@my_dash.name, @user.last_sign_in_at)

%h2 My dash: #{@my_dash.name}

%h3 Campaigns I run

%br
= link_to 'Make New Campaign', new_campaign_path, :class => "btn btn-default btn-xs" 

%br
// = render partial: 'dash_campaigns'
= render partial: 'shared/campaign_list', locals: { campaigns: @dash_hosting }

%br
= link_to 'Join New Game', campaigns_path, :class => "btn btn-default btn-xs"

%br
= render partial: 'shared/player_list', locals: { list: @players }

app/views/dashes/edit.html.haml
%h1 Editing dash

= render 'form'

= link_to 'Show', @dash
\|
= link_to 'Back', dashes_path

app/views/dashes/index.html.haml
%h1 Listing Dashboards

%h3 All dashes
= render partial: 'list_dashes', locals: { list: @dashes_list }

%br
= link_to 'New Dash', new_dash_path

app/views/dashes/new.html.haml
%h1 New dash

= render 'form'

= link_to 'Back', dashes_path

app/views/dashes/show.html.haml
%h1 Showing ...

%p#notice= notice
%ul
  %li= name_id @dash
  %li= dashes_path
  %li 
    Dashboard:
    // = dashboard_path
%p
  %b Name:
  = @dash.name
%p
  %b User:
  = @dash.name
%p
%b Campaigns I run ... (dashcampaigns):
%ul
  - if @dash.campaigns.count > 0 then
    - @dash.campaigns.each do |x|
      %li= x.name
  - else
    Campaigns to see here
%p
  %b Characters to play ... (dashplayers):
%ul  
  - if @dash.players.count > 0 then
    - @dash.players.each do |x|
      %li= x.name
  - else
    No players to see here  

= link_to 'Edit', edit_dash_path(@dash)
\|
= link_to 'Back', dashes_path