config/routes.rb
Rails.application.routes.draw do
  resources :campaign_registrations 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :countries
  devise_for :users #, controllers: { sessions: 'users/registrations' }
  get 'dashboard', to: 'dashes#dashboard'
  resources :dashes 
  resources :campaigns do
   member do
    get 'join'
    get 'leave'
   end
  end
  resources :players
  
  #get 'exit', to: 'sessions#destroy', as: :logout
 
   root "campaigns#index" 
   
  #api
  namespace :api do
    namespace :v1 do
      resources :campaigns
      resources :countries
      resources :players
      resources :dashes
      resources :users
      get 'dashboard', to: 'dashes#dashboard'
    end
  end
   
   # yank later
   resources :neighborhoods
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :centers, class_name:  "Neighborhood",
                                  foreign_key: "target_id",
                                  dependent:   :destroy
  has_many :neighbors, through: :centers, source: :neighbor
  
  has_many  :states
  has_many  :counties, through: :states

  has_many  :playercountries 
  has_many  :players, through: :playercountries, dependent: :destroy
  
  has_many  :campcounts
  has_many  :campaign, through: :campcounts
  
  has_many  :dashcounts #, dependent: :destroy
  has_many  :dashes, through: :dashcounts
  
  validates :name, presence: true 
  #, uniqueness: true  # We remove the uniqueness as countries in different 
  # ... campaigns  need to be able to have same name ... will need a composite 
  # ... key check at some point

  accepts_nested_attributes_for :states, reject_if: proc { |attributes| attributes[:name].blank? }, allow_destroy: true
end

app/controllers/api/v1/countries_controller.rb
class Api::V1::CountriesController < Api::V1::BaseController
  def show
    country = Country.find(params[:id])

    render(json: Api::V1::CountrySerializer.new(country).to_json)
  end
  
  def index
    countries = Country.all

    render(
      json: ActiveModel::Serializer::CollectionSerializer.new(
        countries,
        # each_serializer: Api::V1::CountrySerializer,
        serializer: Api::V1::CountrySerializer,
        root: 'countries',
      )
    )
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.paginate(page: params[:page], per_page: 10)
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
    # @partial_choice = params[:partial_choice]
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update!(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /countries/1
  # # DELETE /countries/1.json
  def destroy
  #   @country.destroy
  #   respond_to do |format|
  #     format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
  #     format.json { head :no_content }
    # end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_country
    @country = Country.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
 def country_params
  params.require(:country).permit(:id, :name, :description, :size, :player_id,
     countryneighbor_attritubtes: [:id, :bordercountry_id, :country_id, :_destroy],
     states_attributes: [:id, :name, :description, :country_id, :_destroy,
     counties_attributes: [:id, :name, :description, :state_id, :_destroy]])
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_country_neighbors.html.haml
// #neighborsDisplay.collapse
//    .list-group
//       - @country.neighbors.each do |x|
// .list-group-item
//   = link_to neighbor.name, edit_country_url(neighbor.id)
   
- if @country.neighbors.count > 0
  %table{:class => "table table-striped table-hover"}
    %thead
      %tr
        %td
          Neighbor ID
        %td
          Neighbor Name
    %tbody
    - for neighbor in @country.neighbors
      %tr
        %td
          = neighbor.id
        %td
          = neighbor.name
        .btn-group-xs	
          %td= link_to 'Show', neighbor, :class => "btn btn-default btn-xs" 
          %td= link_to 'Edit', edit_country_path(neighbor), :class => "btn btn-default btn-xs" 
          %td= link_to neighbor.name, edit_country_url(neighbor.id)

app/views/countries/_county_fields.html.haml
.nested-fields.list-group-item.my-well.well
  .row.text
    = f.input :name, input_html: {:placeholder => "... County Name ..."}
    = f.input :description
    = link_to_remove_association f, class: 'btn btn-default btn-xs' do
      .glyphicon.glyphicon-remove

app/views/countries/_form.html.haml
.fieldset.form-inline
  = simple_form_for @country do |f|
    = f.error_notification
    .countries
      = f.input :name, input_html: {:placeholder => "...insert country name..."}
      = f.input :description
    .row-fuild
      %a.btn.btn-primary{"aria-controls" => "neighborsDisplay", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#neighborsDisplay"} Show Neighbors
      #neighborsDisplay.collapse
        .list-group
          - for neighbor in @country.neighbors
            = render partial: 'country_neighbors', locals: {neighbor: neighbor}
      .states
      = f.simple_fields_for :states do |state|
        = render 'state_fields', :f => state
    .links.row
      = link_to_add_association 'Add State', f, :states,  render_options: { wrapper: 'inline_form' }, :class => "btn btn-default"
    .form-actions.row
      = f.button :submit

app/views/countries/_state_fields.html.haml
.nested-fields.list-group-item
    .well
        %h4 State
        .form-inline.text
            = f.input :name, input_html: {:placeholder => "...insert State Name ..."} 
            = f.input :description
            = link_to_remove_association f, class: 'btn btn-default btn-xs' do
                .glyphicon.glyphicon-remove
        %h4 Counties
        .counties
            = f.simple_fields_for :counties do |state|
                = render 'county_fields', :f => state
            .links.row
                = link_to_add_association 'Add County', f, :counties,  render_options: { wrapper: 'inline_form' }, :class => "btn btn-default"    

app/views/countries/edit.html.haml
%h1 Editing country

= render 'form'

= link_to 'Show', @country
\|
= link_to 'Back', countries_path

app/views/countries/index.html.haml
%h1 Listing countries

%table{:class => "table table-striped table-hover"}  
  %thead
    %tr
      %th Name
      %th Description
      %th Player
  %tbody
    = will_paginate @countries
    - @countries.each do |country|
      %tr
        %td= country.name
        %td= country.description
        .btn-group-xs
          %td= render partial: 'shared/interact_options', locals: { interact_item: country }
          %td= link_to 'Add Neighbors', :neighborhoods, :class => "btn btn-default btn-xs" 
      - if country.neighbors.count > 0
        - for neighbor in country.neighbors
          %tr
            %td
            %td
              = neighbor.id
            %td
              = neighbor.name
            %td
              // = render 'shared/interact_options', locals: { interact_item: neighbor }
= will_paginate @countries

%br
= link_to 'New Country', new_country_path

app/views/countries/new.html.haml
= provide(:title, "Creating")

%h1 New country

= render 'form'

= link_to 'Back', countries_path

app/views/countries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @country.name
%p
  %b Description:
  = @country.description
- if @country.players 
  - @country.players.each do |player|
    %p
      %b Player:
      = name_id player

  
%br

%h2 Neighbors

= render partial: 'country_neighbors', locals: {neighbor: @country}
= link_to 'Edit', edit_country_path(@country)
\|
= link_to 'Back', countries_path