config/routes.rb
Rails.application.routes.draw do
  resources :campaign_registrations 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :countries
  devise_for :users #, controllers: { sessions: 'users/registrations' }
  get 'dashboard', to: 'dashes#dashboard'
  resources :dashes 
  resources :campaigns do
   member do
    get 'join'
    get 'leave'
   end
  end
  resources :players
  
  #get 'exit', to: 'sessions#destroy', as: :logout
 
   root "campaigns#index" 
   
  #api
  namespace :api do
    namespace :v1 do
      resources :campaigns
      resources :countries
      resources :players
      resources :dashes
      resources :users
      get 'dashboard', to: 'dashes#dashboard'
    end
  end
   
   # yank later
   resources :neighborhoods
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  include ActiveModel::Validations

  belongs_to :neighbor, class_name: "Country"
  belongs_to :target, class_name: "Country"
  validates :neighbor_id, presence: true 
  # validates :notItsOwnNeighbor
  validates :target_id, presence: true
    
  # private  
    
#   def notItsOwnNeighbor
#     if :neighbor_id == :target_id 
#       errors.add(:neighbor_id, "cannot neighbor itself ... Original Country: #{target_id}, Neighbor: #{neighbor_id}")  
#     elseif(neighborhood_params[:neighbor_id] == neighborhood_params[:other_id]) 
#       return TRUE
#     else
#       errors.add(:neighbor_id, "ID's were not found for one or both the neighbor & the neighboring country ... Original Country: #{target_id}, Neighbor: #{neighbor_id}") 
#       puts 
#     end
#   end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]

  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully created.' }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { render :new }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json
  def update
    respond_to do |format|
      
      if @neighborhood.update!(neighborhood_params)
    #  if notItSelf? then

        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighborhood }
        # end
      else
        format.html { render :edit }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Neighborhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_neighborhood
    @neighborhood = Neighborhood.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def neighborhood_params
    params.require(:neighborhood).permit(:neighbor_id, :target_id)
  end

end

app/views/neighborhoods/_form.html.haml
= simple_form_for(@neighborhood) do |f|
  = f.error_notification

  .form-inputs
    = f.input :neighbor_id
    = f.input :target_id

  .form-actions
    = f.button :submit

app/views/neighborhoods/edit.html.haml
= provide(:title, "Editing")
%h1 Editing neighborhood

= render 'form'

= link_to 'Show', @neighborhood, :class => "btn xs-btn"

app/views/neighborhoods/index.html.haml
= provide(:title, "Neighbors")

%h1 Listing neighborhoods

%table{:class => "table table-striped table-hover"}
  %thead
    %tr
      %th Target
      %th Neighbor
      %th
      %th
      %th

  %tbody
    - @neighborhoods.each do |neighborhood|
      %tr
        %td= neighborhood.target_id
        %td= neighborhood.neighbor_id
        %td= render partial: 'shared/interact_options', locals: { interact_item: neighborhood }

%br

= link_to 'New Neighborhood', new_neighborhood_path

app/views/neighborhoods/new.html.haml
= provide(:title, "Creating Neighborhoods")
%h1 New neighborhood

= render 'form'

= link_to 'Back', neighborhoods_path

app/views/neighborhoods/show.html.haml
= provide(:title, "Neighorhoods")

%p#notice= notice

%p
  %b Neighbor:
  = @neighborhood.neighbor_id
  // = @neighborhood.neighbor.name
%p
  %b Target:
  = @neighborhood.target_id
  // = @neighborhood.target.name

= link_to 'Edit', edit_neighborhood_path(@neighborhood), :class => "btn xs-btn"