config/routes.rb
Rails.application.routes.draw do
  resources :campaign_registrations 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :countries
  devise_for :users #, controllers: { sessions: 'users/registrations' }
  get 'dashboard', to: 'dashes#dashboard'
  resources :dashes 
  resources :campaigns do
   member do
    get 'join'
    get 'leave'
   end
  end
  resources :players
  
  #get 'exit', to: 'sessions#destroy', as: :logout
 
   root "campaigns#index" 
   
  #api
  namespace :api do
    namespace :v1 do
      resources :campaigns
      resources :countries
      resources :players
      resources :dashes
      resources :users
      get 'dashboard', to: 'dashes#dashboard'
    end
  end
   
   # yank later
   resources :neighborhoods
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :users
  
  has_many  :campaign_registrations
  
  has_many  :campplays
  has_many  :players, through: :campplays
  
  has_many  :campcounts
  has_many  :countries, through: :campcounts
  
  validates :name, presence: true
  default_scope { order(created_at: :desc) }
  
end

app/controllers/api/v1/campaigns_controller.rb
class Api::V1::CampaignsController < Api::V1::BaseController
  def show
    campaign = Campaign.find(params[:id])

    render(json: Api::V1::CampaignSerializer.new(campaign).to_json)
  end
end

app/controllers/campaigns_controller.rb
require 'DomainIdentities.rb'
require 'Enroller.rb'

class CampaignsController < ApplicationController
  include DomainIdentities

  before_action :set_campaign, only: [:join, :edit, :show, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def join
  end
  
  def index
    @campaigns = Campaign.all
    @campaigns = @campaigns.paginate(page: params[:campaigns_page], per_page: 5)
  end

  def show
    @user = setUser
    @dash = setDash

    # Old listings
    @ccountries = @campaign.campcounts.paginate(page: params[:countries_paginate], per_page: 5)
    @players = @campaign.players.paginate(page: params[:players_paginate], per_page: 5)
  end

  def new
    @dash = setDash
    @campaign =  @dash.campaigns.build
  end

  def edit
  end

  def create
  @dash = setDash
    # @campaign = @dash.campaigns.create!(campaign_params)  # works v1
# User.second.dashes.first.campaigns.create(name: "blah2")
    respond_to do |format|
      # if @campaign.save  # works v1
      if @campaign = @dash.campaigns.create!(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @campaign.update!(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy

    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
  def set_user
    @user = User.find(current_user.id)
  end
  
  def set_campaign
    # @campaign = Campaign.find(params[:id])
    @campaign = Campaign.find(params[:id])
  end

    def campaign_params
      params.require(:campaign).permit(:name, :description, :player_id)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
    def join_helper(campaign)
        # campaign_registrations_path(campaign_id: campaign)
        link_to "Join", campaign_registrations_path(campaign_id: campaign), 
        method: :post, :class => "btn btn-xs btn-default"
    end
end

app/views/campaigns/_form.html.haml
= simple_form_for(@campaign) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/campaigns/edit.html.haml
= provide(:title, "Edit Campaign")
%h1 Editing campaign

= render 'form'

= link_to 'Show', @campaign
\|
= link_to 'Back', campaigns_path

app/views/campaigns/index.html.haml
= provide(:title, "Campaigns")

%br

.listings
  - if @campaigns.count > 0
    = will_paginate @campaigns, :param_name => "campaigns_page"
    = render partial: 'shared/campaign_list.html.haml', locals: { campaigns: @campaigns }
  - else
    = "No active campaigns found."
%br

= link_to 'New Campaign', new_campaign_path, :class => "btn btn-md btn-default"

app/views/campaigns/new.html.haml
= provide(:title, "New Campaign")

%h1 New campaign

= render 'form'

= link_to 'Back', campaigns_path

app/views/campaigns/show.html.haml
= provide(:title, "Campaigns")

%p#notice= notice

.jumbotron.campaigndetails
  %h1= @campaign.name
  %p= @campaign.description
  %ul
  - if @dash.present?
    %li
      = @dash.name
    %li
      = email_name @dash.users.first


.hoster
  %h2= "#{@user.name} runs this..."
  %br
  = join_helper(@campaign.id)

  %br

.players
  = render partial: 'shared/player_list', locals: { list: @players }

.countries
  %h2
    Countries List
  - if @ccountries.count > 0
    %table{:class => "table table-striped table-hover"}
      %tbody
      - @ccountries.each do |joinedc|
        %tr
          %td= joinedc.country.name
          %td= link_to "Show", country_url(joinedc.country)
          %td= link_to "Edit", edit_country_url(joinedc.country.id)
      = will_paginate @ccountries

  - else
    %p
      No countries found...
%p= link_to 'Edit', edit_campaign_path(@campaign), :class => "btn xs-btn"